<?php

namespace App\Tests\Domain;

use App\Domain\Board;
use App\Domain\ThreeInARowResult;
use App\Domain\TilePosition;
use Exception;
use PHPUnit\Framework\TestCase;

class BoardTest extends TestCase
{
    private Board $board;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->board = new Board();
    }

    public function ThreeNonInARowDataProvider(): array
    {
        return [
            [[new TilePosition(1, 1), new TilePosition(2, 1), new TilePosition(1, 3)]],
            [[new TilePosition(2, 1), new TilePosition(1, 2), new TilePosition(2, 3)]],
            [[new TilePosition(3, 3), new TilePosition(3, 2), new TilePosition(1, 3)]]
        ];
    }

    public function ThreeInARowDataProvider(): array
    {
        return [
            [[new TilePosition(1, 1), new TilePosition(1, 2), new TilePosition(1, 3)]],
            [[new TilePosition(2, 1), new TilePosition(2, 2), new TilePosition(2, 3)]],
            [[new TilePosition(3, 1), new TilePosition(3, 2), new TilePosition(3, 3)]],
            [[new TilePosition(1, 1), new TilePosition(2, 1), new TilePosition(3, 1)]],
            [[new TilePosition(1, 2), new TilePosition(2, 2), new TilePosition(3, 2)]],
            [[new TilePosition(1, 3), new TilePosition(2, 3), new TilePosition(3, 3)]],
            [[new TilePosition(1, 1), new TilePosition(2, 2), new TilePosition(3, 3)]],
            [[new TilePosition(3, 1), new TilePosition(2, 2), new TilePosition(1, 3)]]
        ];
    }

    /**
     * @return TilePosition[]
     *
     */
    public function inRangePositionDataProvider(): array
    {
        return [
            [new TilePosition(1, 1)],
            [new TilePosition(1, 2)],
            [new TilePosition(1, 3)],
            [new TilePosition(2, 1)],
            [new TilePosition(2, 2)],
            [new TilePosition(2, 3)],
            [new TilePosition(3, 1)],
            [new TilePosition(3, 2)],
            [new TilePosition(3, 3)]
        ];
    }

    public function outOfRangePositionDataProvider(): array
    {
        return [
            [new TilePosition(0, -1)],
            [new TilePosition(0, 0)],
            [new TilePosition(0, 1)],
            [new TilePosition(0, 2)],
            [new TilePosition(0, 3)],
            [new TilePosition(0, 4)],
            [new TilePosition(0, 5)],
            [new TilePosition(-1, 0)],
            [new TilePosition(0, 0)],
            [new TilePosition(1, 0)],
            [new TilePosition(2, 0)],
            [new TilePosition(3, 0)],
            [new TilePosition(4, 0)],
            [new TilePosition(5, 0)]
        ];
    }

    /**
     * @dataProvider inRangePositionDataProvider
     */
    public function test_setTileAsX_mustTileBeMarkedAsX(TilePosition $position)
    {
        $this->board->markTileAsO($position);

        self::assertTrue($this->board->isTileMarkedAsO($position));
    }

    /**
     * @dataProvider inRangePositionDataProvider
     */
    public function test_setTileAsX_mustTileBeMarkedAsY(TilePosition $position)
    {
        $this->board->markTileAsX($position);

        self::assertTrue($this->board->isTileMarkedAsX($position));
    }


    /**
     * @dataProvider outOfRangePositionDataProvider
     */
    public function test_setTileAsX_PositionNotValid_mustThrowException(TilePosition $position)
    {
        self::expectException(Exception::class);
        $this->board->markTileAsX($position);
    }

    /**
     * @dataProvider outOfRangePositionDataProvider
     */
    public function test_setTileAsO_PositionNotValid_mustThrowException(TilePosition $position)
    {
        self::expectException(Exception::class);
        $this->board->markTileAsO($position);
    }

    /**
     * @dataProvider ThreeInARowDataProvider
     * @param TilePosition[] $threeTilePosition
     */
    public function test_ThreeInARowO(array $threeTilePosition)
    {
        foreach ($threeTilePosition as $item) {
            $this->board->markTileAsO($item);
        }

        $res = $this->board->checkThreeInARaw();

        self::assertTrue($res->result());
        self::assertTrue($res->isO());
    }

    /**
     * @dataProvider ThreeInARowDataProvider
     * @param TilePosition[] $threeTilePosition
     */
    public function test_ThreeInARowX(array $threeTilePosition)
    {
        foreach ($threeTilePosition as $item) {
            $this->board->markTileAsX($item);
        }

        $res = $this->board->checkThreeInARaw();

        self::assertTrue($res->result());
        self::assertTrue($res->isX());
    }

    /**
     * @dataProvider ThreeNonInARowDataProvider
     * @param TilePosition[] $threeTilePosition
     */
    public function test_ThreeNoInARowX(array $threeTilePosition)
    {
        foreach ($threeTilePosition as $item) {
            $this->board->markTileAsX($item);
        }

        $res = $this->board->checkThreeInARaw();

        self::assertFalse($res->result());
        self::assertFalse($res->isX());
        self::assertFalse($res->isO());
    }

    public function test_isClear_trueScenario()
    {
        self::assertTrue($this->board->isClean());
    }

    public function test_isClear_falseScenario()
    {
        $this->board->markTileAsO(new TilePosition(1, 1));
        self::assertFalse($this->board->isClean());
    }

    public function test_cleanBoard()
    {
        $this->board->markTileAsO(new TilePosition(1, 1));
        $this->board->clearBoard();

        self::assertTrue($this->board->isClean());
    }

}


