<?php

namespace App\Tests\Domain;

use App\Game\Domain\Board;
use App\Game\Domain\Mark;
use App\Game\Domain\Player;
use PHPUnit\Framework\TestCase;
use function Symfony\Component\DependencyInjection\Loader\Configurator\service_locator;

class PlayerTest extends TestCase
{
    private Player $player;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_sameMarkOf_trueScenario(){
        $player1 = new Player("player1", Mark::createAsXMark());
        $player2 = new Player("player2", Mark::createAsXMark());

        self::assertTrue($player1->sameMarkOf($player2));
    }

    public function test_sameMarkOf_falseScenario(){
        $player1 = new Player("player1", Mark::createAsXMark());
        $player2 = new Player("player2", Mark::createAsOMark());

        self::assertFalse($player1->sameMarkOf($player2));
    }

}
