<?php

namespace App\Tests\Domain;

use App\Domain\Board;
use App\Domain\Player;
use PHPUnit\Framework\TestCase;
use function Symfony\Component\DependencyInjection\Loader\Configurator\service_locator;

class PlayerTest extends TestCase
{
    private Player $player;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_createOPlayer(){
        $player = Player::createOPlayer("playerO", new Board());

        self::assertTrue($player->isO());
        self::assertFalse($player->isX());
    }

    public function test_createXPlayer(){
        $player = Player::createXPlayer("playerX", new Board());

        self::assertFalse($player->isO());
        self::assertTrue($player->isX());
    }

}
