<?php

namespace App\Tests\Game\Domain;

use App\Game\Domain\Model\Board;
use App\Game\Domain\Model\Mark;
use App\Game\Domain\Model\Player;
use PHPUnit\Framework\TestCase;
use function Symfony\Component\DependencyInjection\Loader\Configurator\service_locator;

class PlayerTest extends TestCase
{
    private Player $player;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_sameMarkOf_trueScenario(){
        $player1 = new Player("player1", "fa05b2ac-5988-42d6-a48d-ee62ad63ad01",Mark::createAsXMark());
        $player2 = new Player("player2", "fa05b2ac-5988-42d6-a48d-ee62ad63ad02",Mark::createAsXMark());

        self::assertTrue($player1->sameMarkOf($player2));
    }

    public function test_sameMarkOf_falseScenario(){
        $player1 = new Player("player1", "fa05b2ac-5988-42d6-a48d-ee62ad63ad01",Mark::createAsXMark());
        $player2 = new Player("player2", "fa05b2ac-5988-42d6-a48d-ee62ad63ad02",Mark::createAsOMark());

        self::assertFalse($player1->sameMarkOf($player2));
    }

}
